import { supabase } from "./supabaseClient.js";
import fs from "fs";
import csv from "csv-parser";
import dotenv from "dotenv";

dotenv.config();

// ---------- CSV Loader ----------
async function loadCSV(path) {
  return new Promise((resolve, reject) => {
    const rows = [];
    fs.createReadStream(path)
      .pipe(csv())
      .on("data", (row) => {
        for (const key in row) {
          if (row[key] === "") row[key] = null;
        }
        rows.push(row);
      })
      .on("end", () => resolve(rows))
      .on("error", (err) => reject(err));
  });
}

// ---------- Insert Helper ----------
async function insertData(table, rows) {
  console.log(`\n➡️ Inserting into ${table} (${rows.length} rows)...`);

  if (rows.length === 0) {
    console.log(`⚠️ Skipping ${table} — CSV is empty.`);
    return;
  }

  const { error } = await supabase.from(table).insert(rows);

  if (error) {
    console.error(`❌ Error inserting into ${table}:`, error.message);
    process.exit(1);
  }

  console.log(`✅ ${table} inserted successfully.`);
}

// ---------- CSV Auto-Creation ----------
function ensureCSV(path, headers) {
  if (!fs.existsSync(path)) {
    console.log(`📄 Creating missing CSV file: ${path}`);

    const dir = path.substring(0, path.lastIndexOf("/"));
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(path, headers.join(",") + "\n");
  }
}

// ---------- MAIN ----------
async function main() {
  console.log("=== Supabase CSV Data Loader (JS) ===");

  // -----------------------------
  // CREATE CSVs IF MISSING
  // -----------------------------

  ensureCSV("./data/Staff.csv", [
    "StaffID",
    "StaffSSN",
    "FName",
    "Minit",
    "LName",
    "PhoneNo",
    "Email",
    "Position",
  ]);

  ensureCSV("./data/Doctor.csv", [
    "DoctorID",
    "Specialization",
    "MedicalLicNo",
  ]);

  ensureCSV("./data/Nurse.csv", [
    "NurseID",
    "NurseLicNo",
    "ShiftType",
    "Ward",
  ]);

  ensureCSV("./data/Patient.csv", [
    "PatientID",
    "PatientSSN",
    "FName",
    "Minit",
    "LName",
    "Gender",
    "DOB",
    "Address",
    "Email",
    "PhoneNo",
    "PrimaryDocID",
    "Insurance",
  ]);

  ensureCSV("./data/Appointment.csv", [
    // SERIAL PK generated by DB → exclude AppointmentID
    "ApptReason",
    "ApptDateTime",
    "ApptNotes",
    "IsCompleted",
    "PatientID",
    "DoctorID",
  ]);

  ensureCSV("./data/Lab_Results.csv", [
    // SERIAL PK generated by DB → exclude LabResID
    "TestDate",
    "TestType",
    "ResultNotes",
    "PatientID",
    "NurseID",
    "DoctorID",
  ]);

  ensureCSV("./data/Treatment.csv", [
    // SERIAL PK generated by DB → exclude TreatmentID
    "PatientID",
    "DoctorID",
    "TreatmentType",
    "StartDate",
    "EndDate",
  ]);

  // -----------------------------
  // LOAD CSV Contents
  // -----------------------------
  const staff = await loadCSV("./data/Staff.csv");
  const doctor = await loadCSV("./data/Doctor.csv");
  const nurse = await loadCSV("./data/Nurse.csv");
  const patient = await loadCSV("./data/Patient.csv");
  const appointment = await loadCSV("./data/Appointment.csv");
  const labResults = await loadCSV("./data/Lab_Results.csv");
  const treatment = await loadCSV("./data/Treatment.csv");

  // -----------------------------
  // INSERT IN FK-CORRECT ORDER
  // -----------------------------
  await insertData("staff", staff);
  await insertData("doctor", doctor);
  await insertData("nurse", nurse);
  await insertData("patient", patient);
  await insertData("appointment", appointment);
  await insertData("lab_results", labResults);
  await insertData("treatment", treatment);

  console.log("\n🎉 All data loaded successfully!");
  process.exit(0);
}

main().catch((err) => console.error(err));
